CREATE TABLE soc1 (
    id INTEGER PRIMARY KEY,
    department TEXT
);

ALTER TABLE soc1 RENAME TO SECURITY_OPERATION_CENTER;

ALTER TABLE SECURITY_OPERATION_CENTER
ADD COLUMN count_employees INTEGER;

INSERT INTO SECURITY_OPERATION_CENTER (department, count_employees)
VALUES ('SOC Tier 1', 20 );

INSERT INTO SECURITY_OPERATION_CENTER (department, count_employees)
VALUES ('SOC Tier 2', 25 );

INSERT INTO SECURITY_OPERATION_CENTER (department, count_employees)
VALUES ('SOC Tier 3', 10 );

UPDATE SECURITY_OPERATION_CENTER
SET count_employees = 21
WHERE department = 'SOC Tier 3';

DELETE FROM SECURITY_OPERATION_CENTER
WHERE id = 2;